--- #YAML:1.0
name:               KiokuDB-Backend-DBI
version:            1.11_02
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Stream::Bulk:   0.07
    DBI:                  1.607
    DBIx::Class:          0.08120
    KiokuDB:              0.39
    Moose:                0
    MooseX::Types:        0.08
    MooseX::Types::Moose:  0
    Search::GIN:          0
    SQL::Abstract:        0
    SQL::Translator:      0.11005
    Test::More:           0.88
    Test::TempDir:        0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
