--- #YAML:1.0
name:               KiokuDB-Backend-DBI
version:            0.01
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Stream::Bulk:   0
    DBIx::Class:          0.08010
    KiokuDB:              0.10
    Moose:                0
    MooseX::Types::Moose:  0
    Search::GIN:          0
    SQL::Abstract:        0
    Test::More:           0
    Test::TempDir:        0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
